name: Visualis3D
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5985663
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Digital Visualisation Company
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#656565'
    - '#222222'
    - '#fcfcfc'
    - '#adadad'
  brandStrength: 0.5
  lightness: 0.5107527
  saturation: 1
  rhythmicContrast: 1
purpose: []
