name: Visualis3D
favicon: null
layout_spectrum: 0.24659
typography_spectrum: 0.1487455
title: Digital Visualisation Company
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#54a5d2'
    - '#3069a0'
    - '#b5dbff'
    - '#292e32'
  brandStrength: 0.25
  lightness: 0.8125
  saturation: 0.9375
  rhythmicContrast: 0.5
purpose: []
