title: Digital Visualisation Company
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.8351235
  brandStrength: 0.1658250945620239
  lightness: 0.3238453
  brandColors:
    - '#6083BD'
    - '#BC9F7F'
    - '#0C0F16'
    - '#EFF3FE'
    - '#2B4755'
  rhythmicContrast: 0.4065521
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
cta:
  bucket: null
  version: null
  domain: null
name: Visualis3D
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.2290664145257324
layout_spectrum: 0.9973147
